spring:
  application:
    name: user-service
    version: @project.version@
  datasource:
    host: localhost
    port: 5432
    database: mydatabase
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
server:
  port: 8081
